Repository scalecube/scalecube-configuration-service, pull requests merged in 2019-01, with the labels that each got.

#47 Develop API docs - configuration service
  API-Calls-examples.json
  ApiDocs/_apidoc.js
  ApiDocs/apidoc-template.json
  ApiDocs/apidoc.json
  ApiDocs/common.apidoc
  ApiDocs/create.apidoc
  ApiDocs/datatypes.apidoc
  ApiDocs/delete.apidoc
  ApiDocs/entries.apidoc
  ApiDocs/fetch.apidoc
  ApiDocs/overview.apidoc
  ApiDocs/save.apidoc
  src/main/scripts/cd/release-generate-docs.sh
Labels: ready for review

#31 added mpa-7103 - basic CRUD tests for configuration service
  scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
Labels: feature file

#63 fix for #62
  pom.xml
Labels: Security

#60 Develop api docs update
  API-Calls-examples.json
  ApiDocs/apidoc-template.json
  ApiDocs/create.apidoc
  ApiDocs/entries.apidoc
  ApiDocs/fetch.apidoc
  ApiDocs/overview.apidoc
Labels: enhancement

#57 Clean up `pom.xml` and `Dockerfile`
  pom.xml
  scalecube-configuration-api/pom.xml
  scalecube-configuration/Dockerfile
  scalecube-configuration/pom.xml
Labels: ready for review

#79 Api doc update
  ApiDocs/_apidoc.js
  ApiDocs/create.apidoc
  ApiDocs/delete.apidoc
  ApiDocs/entries.apidoc
  ApiDocs/fetch.apidoc
  ApiDocs/overview.apidoc
  ApiDocs/save.apidoc
Labels: enhancement

#78 Refactoring of configuration mechanism
  scalecube-configuration/src/main/java/io/scalecube/configuration/AppConfiguration.java
  scalecube-configuration/src/main/java/io/scalecube/configuration/AppSettings.java
  scalecube-configuration/src/main/java/io/scalecube/configuration/AppSettingsException.java
  scalecube-configuration/src/main/java/io/scalecube/configuration/ConfigRegistryConfiguration.java
  scalecube-configuration/src/main/java/io/scalecube/configuration/tokens/KeyProviderFactory.java
  scalecube-configuration/src/main/java/io/scalecube/configuration/tokens/VaultKeyProvider.java
  scalecube-configuration/src/main/java/io/scalecube/configuration/tokens/VaultPathBuilder.java
  scalecube-configuration/src/main/java/io/scalecube/server/ConfigurationServiceRunner.java
  scalecube-configuration/src/main/java/io/scalecube/server/DiscoveryOptions.java
  scalecube-configuration/src/main/resources/app.config.properties
  scalecube-configuration/src/main/resources/couchbase.config.properties
  scalecube-configuration/src/main/resources/discovery.config.properties
  scalecube-configuration/src/main/resources/settings.props
Labels: enhancement, ready for review

#83 Api doc removed host url
  API-Calls-examples.json
  ApiDocs/_apidoc.js
  ApiDocs/apidoc.json
  ApiDocs/create.apidoc
  ApiDocs/delete.apidoc
  ApiDocs/entries.apidoc
  ApiDocs/fetch.apidoc
  ApiDocs/overview.apidoc
  ApiDocs/save.apidoc
Labels: enhancement

#86 API doc update
  API-Calls-examples.json
  ApiDocs/_apidoc.js
  ApiDocs/apidoc.json
  ApiDocs/create.apidoc
  ApiDocs/delete.apidoc
  ApiDocs/entries.apidoc
  ApiDocs/fetch.apidoc
  ApiDocs/overview.apidoc
  ApiDocs/save.apidoc
  scalecube-configuration-api/src/main/java/io/scalecube/configuration/api/ConfigurationService.java
  src/main/scripts/cd/deploy.sh
  src/main/scripts/cd/release.sh
Labels: enhancement, ready for review

#77 ConfigurationService benchmarks
  pom.xml
  scalecube-configuration-benchmarks/Dockerfile
  scalecube-configuration-benchmarks/pom.xml
  scalecube-configuration-benchmarks/src/main/java/io/scalecube/configuration/benchmarks/ConfigurationServiceBenchmarkState.java
  scalecube-configuration-benchmarks/src/main/java/io/scalecube/configuration/benchmarks/ReadConfigValueBenchmark.java
  scalecube-configuration-benchmarks/src/main/java/io/scalecube/configuration/benchmarks/UpdateConfigValueBenchmark.java
Labels: enhancement, ready for review
